CREATE DATABASE IF NOT EXISTS `codeigniter3_api` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `codeigniter3_api`;

CREATE TABLE IF NOT EXISTS `product` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `title` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=51 ;

INSERT INTO `product` (`id`, `title`) VALUES
(1, 'ipsum'),
(2, 'egestas.'),
(3, 'a'),
(4, 'erat'),
(5, 'augue.'),
(6, 'quis'),
(7, 'Cras'),
(8, 'aliquet'),
(9, 'Phasellus'),
(10, 'varius'),
(11, 'In'),
(12, 'in'),
(13, 'cubilia'),
(14, 'eget,'),
(15, 'Sed'),
(16, 'ornare.'),
(17, 'euismod'),
(18, 'eget'),
(19, 'imperdiet'),
(20, 'eu'),
(21, 'eget'),
(22, 'a'),
(23, 'sodales'),
(24, 'Phasellus'),
(25, 'Curabitur'),
(26, 'neque'),
(27, 'in'),
(28, 'nascetur'),
(29, 'pharetra'),
(30, 'euismod'),
(31, 'amet'),
(32, 'egestas'),
(33, 'arcu.'),
(34, 'metus'),
(35, 'egestas,'),
(36, 'est.'),
(37, 'amet'),
(38, 'amet'),
(39, 'luctus'),
(40, 'Proin'),
(41, 'volutpat'),
(42, 'blandit'),
(43, 'Aenean'),
(44, 'vulputate,'),
(45, 'interdum'),
(46, 'parturient'),
(47, 'lobortis,'),
(48, 'Cras'),
(49, 'dictum'),
(50, 'Sed');